mgr/influx: Catch ConnectionError if raised
The InfluxDBClient can also re-raise a ConnectionError from the
python requests module if that was caught.

The Exception might be:

  ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

Catch and log this error instead of having it raised which might
cause problems further down.

Signed-off-by: Wido den Hollander <wido@42on.com>